Update to 1.20.2
kkllffaa/meteor-litematica-printer pull request #24
Opened 2023-10-13 02:51 UTC by RedCarlos26

2023-12-26 16:37 UTC, TherealONE12 commented
I cant download it. pls help me

2023-12-27 18:16 UTC, RedCarlos26 commented
It hasn't been merged yet

2024-01-05 04:24 UTC, Oogaboogaman21 commented
Yes 1.20.2 PLEASE

2024-01-05 04:30 UTC, Oogaboogaman21 requested changes
Yes

2024-01-17 04:07 UTC, closed without merging